import { featureBranches as b, projectConfig as c, type LearnerId } from "@/config/project";

export type TaskKind = "learn" | "follow" | "challenge";
export type Task = { id:string; kind:TaskKind; title:string; description:string; assignee:LearnerId|"both"; steps:string[]; code?:string; file?:string; links?:{label:string;url:string}[] };
export type Stage = { id:string; number:string; eyebrow:string; title:string; summary:string; duration:string; color:"mint"|"peach"|"lilac"|"blue"; tasks:Task[]; checkpoint:string[] };
const table=(name:string)=>`${c.projectCatalog}.${c.developmentSchema}.${name}`;
const docs={
  free:{label:"Free Edition guide",url:c.freeEditionGuideUrl}, data:{label:"NYC taxi sample",url:c.sourceDataUrl}, git:{label:"Git folders guide",url:c.gitFoldersGuideUrl},
  notebook:{label:"Notebook guide",url:c.notebooksGuideUrl}, medallion:{label:"Medallion guide",url:c.medallionGuideUrl}, dashboard:{label:"Dashboard tutorial",url:"https://docs.databricks.com/aws/en/dashboards/tutorials/create-dashboard"},
  jobs:{label:"Lakeflow Jobs guide",url:c.jobsGuideUrl}, terraform:{label:"Databricks Terraform provider",url:"https://registry.terraform.io/providers/databricks/databricks/latest/docs"},
};
const videos={
  start:{label:"Video · Free Edition beginner setup",url:"https://www.youtube.com/watch?v=GGqQqjLrJYI"},
  medallion:{label:"Video · Bronze, Silver & Gold",url:"https://www.youtube.com/watch?v=T0Wys-RULYM"},
  dashboard:{label:"Video · Build an AI/BI dashboard",url:"https://www.youtube.com/watch?v=dTH_WrFNM2g"},
  terraform:{label:"Video · Terraform for beginners",url:"https://www.youtube.com/watch?v=Bzccj0jjRBM"},
};

export const stages:Stage[]=[
  {id:"setup",number:"01",eyebrow:"Start here",title:"Get ready",summary:"Create your account, open the project, and learn where things are.",duration:"45 min",color:"mint",tasks:[
    {id:"welcome",kind:"learn",title:"What you are building",assignee:"both",description:"CityRide turns taxi trips into clean tables, useful numbers, and a dashboard.",steps:["Watch the short beginner tour.","Open Databricks in another tab.","Find Workspace, Catalog, SQL Editor, and Jobs & Pipelines.","Come back when those four areas feel familiar."],links:[videos.start,docs.free]},
    {id:"access-v",kind:"follow",title:"Viri: open your accounts",assignee:"viri",description:"Use your own Databricks and GitHub accounts.",steps:["Create a Free Edition account if needed.","Accept the workspace invitation.","Accept the CityRide GitHub invitation.","Open both links once."],links:[{label:"Create Free Edition account",url:c.databricksFreeEditionSignupUrl},{label:"CityRide repository",url:c.repositoryUrl}]},
    {id:"access-i",kind:"follow",title:"Isabel: open your accounts",assignee:"isabel",description:"Use your own Databricks and GitHub accounts.",steps:["Create a Free Edition account if needed.","Accept the workspace invitation.","Accept the CityRide GitHub invitation.","Open both links once."],links:[{label:"Create Free Edition account",url:c.databricksFreeEditionSignupUrl},{label:"CityRide repository",url:c.repositoryUrl}]},
    {id:"git-v",kind:"follow",title:"Viri: make your Git folder",assignee:"viri",description:"Each person needs a separate copy of the repository.",steps:["Open Settings → Linked accounts and connect GitHub.","Open your personal Workspace folder.","Choose Create → Git folder.",`Paste ${c.repositoryUrl}.`,"Check that README.md, notebooks, sql, tests, and docs appear."],links:[docs.git]},
    {id:"git-i",kind:"follow",title:"Isabel: make your Git folder",assignee:"isabel",description:"Do not use Viri's Git folder.",steps:["Open Settings → Linked accounts and connect GitHub.","Open your personal Workspace folder.","Choose Create → Git folder.",`Paste ${c.repositoryUrl}.`,"Check that README.md, notebooks, sql, tests, and docs appear."],links:[docs.git]},
  ],checkpoint:["Both accounts work","Each person has a separate Git folder","You can find the four main Databricks areas"]},

  {id:"python",number:"02",eyebrow:"Learn",title:"Warm up with Python",summary:"Run a few tiny commands before touching the taxi data.",duration:"45–60 min",color:"blue",tasks:[
    {id:"python-notebook",kind:"learn",title:"How notebook cells work",assignee:"both",description:"A notebook runs code one cell at a time and keeps the results below each cell.",steps:["Open notebooks/00_explore_source.py.","Connect to Serverless compute when asked.","Use Shift+Enter to run a cell.","Notice the result directly below the code."],links:[docs.notebook]},
    {id:"python-basics",kind:"follow",title:"Run simple Python",assignee:"viri",description:"Start with values you already know from regular Python.",steps:["Add the code in a new Python cell.","Run it.","Change team_name to another value and run it again.","Explain what the list contains."],code:`team_name = "CityRide"\ntrip_goal = 100\nmetrics = ["trip count", "average fare", "total fare"]\n\nprint(team_name)\nprint(f"Trip goal: {trip_goal}")\nprint(metrics)`},
    {id:"spark-small",kind:"follow",title:"Make a tiny Spark table",assignee:"isabel",description:"Spark DataFrames look like tables. Start with only five rows.",steps:["Run the code.","Look at the id column.","Change 5 to 10.","Run it again and explain what changed."],code:`numbers_df = spark.range(5)\ndisplay(numbers_df)`},
    {id:"python-challenge",kind:"challenge",title:"Challenge: keep the even numbers",assignee:"both",description:"Try this together before opening any taxi data.",steps:["Start with spark.range(10).","Use filter to keep rows where id % 2 == 0.","Display the answer.","You should see 0, 2, 4, 6, and 8."],code:`numbers_df = spark.range(10)\neven_df = numbers_df.filter("id % 2 = 0")\ndisplay(even_df)`},
  ],checkpoint:["Run a Python cell","Display a Spark DataFrame","Explain the difference between code and its result"]},

  {id:"explore",number:"03",eyebrow:"Follow along",title:"Meet the taxi data",summary:"Look at a few rows first. Then ask simple questions about them.",duration:"60 min",color:"peach",tasks:[
    {id:"load-source",kind:"follow",title:"Open ten taxi trips",assignee:"both",description:`The data is already available as ${c.sourceTable}.`,steps:["Add the code below.","Run it.","Scroll across the ten rows.","Pick one row and describe the trip in plain English."],code:`trips = spark.read.table("${c.sourceTable}")\ndisplay(trips.limit(10))`,links:[docs.data]},
    {id:"select-columns",kind:"follow",title:"Choose five useful columns",assignee:"isabel",description:"A smaller view is easier to understand.",steps:["Select the five columns below.","Display ten rows.","Find the pickup time, distance, fare, and ZIP codes.","Say what each column tells you."],code:`simple_trips = trips.select(\n    "tpep_pickup_datetime",\n    "trip_distance",\n    "fare_amount",\n    "pickup_zip",\n    "dropoff_zip"\n)\n\ndisplay(simple_trips.limit(10))`},
    {id:"simple-counts",kind:"follow",title:"Count and summarize",assignee:"viri",description:"Use two simple actions to learn about the table.",steps:["Count all rows.","Run describe on distance and fare.","Find the average fare in the result.","Do not worry about memorizing every number."],code:`print(f"Rows: {trips.count():,}")\ndisplay(trips.select("trip_distance", "fare_amount").describe())`},
    {id:"explore-challenge",kind:"challenge",title:"Challenge: find a data problem",assignee:"both",description:"Real data is rarely perfect.",steps:["Look for a negative fare, zero distance, missing ZIP, or unusual time.","Write down one example.","Write one question a taxi manager might ask.",`Create ${b.sourceExploration}, commit the notes, and open a pull request.`]},
  ],checkpoint:["Explain one taxi row","Name five useful columns","Find one possible data problem","Write one business question"]},

  {id:"medallion",number:"04",eyebrow:"Learn + follow",title:"Build Bronze",summary:"Learn the three-layer idea, then save the original trips as Bronze.",duration:"60–90 min",color:"lilac",tasks:[
    {id:"learn-medallion",kind:"learn",title:"Bronze, Silver, Gold",assignee:"both",description:"Bronze keeps the original, Silver cleans the details, and Gold answers questions.",steps:["Watch the Bronze–Silver–Gold video.","Open the official diagram.","Explain each layer using one sentence.","Match CityRide's three table types to the layers."],links:[videos.medallion,docs.medallion]},
    {id:"layer-challenge",kind:"challenge",title:"Challenge: place each action",assignee:"both",description:"Decide which layer should do each job.",steps:["Save the source exactly as received → Bronze.","Remove negative fares → Silver.","Count trips by day → Gold.","Discuss why the dashboard should use Gold."]},
    {id:"bronze",kind:"follow",title:"Save the Bronze table",assignee:"viri",description:"Bronze is the starting copy. Keep it simple.",file:"notebooks/01_bronze.py",steps:[`Pull main and create ${b.bronzeIngestion}.`,`Select ${c.projectCatalog}.${c.developmentSchema}.`,"Read the sample trips.","Add the copied_at column.","Save and display ten rows."],code:`from pyspark.sql import functions as F\n\nspark.sql("USE CATALOG ${c.projectCatalog}")\nspark.sql("USE SCHEMA ${c.developmentSchema}")\n\nbronze = (\n    spark.read.table("${c.sourceTable}")\n    .withColumn("copied_at", F.current_timestamp())\n)\n\nbronze.write.mode("overwrite").saveAsTable("${table("bronze_trips")}")\ndisplay(spark.table("${table("bronze_trips")}").limit(10))`},
    {id:"bronze-review",kind:"challenge",title:"Isabel checks Bronze",assignee:"isabel",description:"A review is a second pair of eyes, not a test.",steps:["Open Viri's pull request.","Check that the source is unchanged except for copied_at.","Ask Viri to run all cells once more.","Approve and merge when it works."]},
  ],checkpoint:["Explain all three layers","Bronze exists in cityride.dev","Bronze still looks like the source","The branch is merged"]},

  {id:"silver",number:"05",eyebrow:"Follow + challenge",title:"Clean Silver",summary:"Make the trip details easier and safer to use.",duration:"90 min",color:"blue",tasks:[
    {id:"silver-learn",kind:"learn",title:"What Silver changes",assignee:"both",description:"Silver fixes types, removes duplicates, and filters values that do not make sense.",steps:["Read the three cleaning rules below.","Discuss what each rule removes.","Agree that the detailed trip rows should remain detailed.","Write the rules in docs/data_dictionary.md."],links:[docs.medallion]},
    {id:"silver-build",kind:"follow",title:"Build Silver one rule at a time",assignee:"isabel",description:"Run and inspect after each filter instead of adding everything at once.",file:"notebooks/02_silver.py",steps:[`Pull main and create ${b.silverCleaning}.`,"Read bronze_trips.","Cast distance and fare to numbers.","Keep non-negative fares and distances.","Remove duplicate rows, save Silver, and preview it."],code:`from pyspark.sql import functions as F\n\nbronze = spark.table("${table("bronze_trips")}")\n\nsilver = (\n    bronze\n    .withColumn("trip_distance", F.col("trip_distance").cast("double"))\n    .withColumn("fare_amount", F.col("fare_amount").cast("double"))\n    .filter(F.col("trip_distance") >= 0)\n    .filter(F.col("fare_amount") >= 0)\n    .dropDuplicates()\n)\n\nsilver.write.mode("overwrite").saveAsTable("${table("silver_trips")}")\ndisplay(silver.limit(10))`},
    {id:"silver-compare",kind:"challenge",title:"Challenge: what changed?",assignee:"viri",description:"Compare Bronze and Silver without changing Isabel's code.",steps:["Count Bronze.","Count Silver.","Subtract the two counts.","Explain why Silver can have fewer rows.","Review and merge the pull request."],code:`bronze_count = spark.table("${table("bronze_trips")}").count()\nsilver_count = spark.table("${table("silver_trips")}").count()\n\nprint(f"Bronze: {bronze_count:,}")\nprint(f"Silver: {silver_count:,}")\nprint(f"Removed: {bronze_count - silver_count:,}")`},
  ],checkpoint:["Explain the Silver rules","Silver contains detailed trips","Compare Bronze and Silver counts","The branch is merged"]},

  {id:"gold",number:"06",eyebrow:"Learn + challenge",title:"Create useful metrics",summary:"Decide what the numbers mean before building Gold.",duration:"90 min",color:"peach",tasks:[
    {id:"metrics-learn",kind:"learn",title:"What is a metric?",assignee:"both",description:"A metric is a number with a clear meaning, such as trips per day or average fare.",steps:["Define trip_count: number of trips in a group.","Define avg_fare: average fare in that group.","Define total_fare: all fares added together.","Decide who might use each metric.","Write the definitions in the data dictionary."]},
    {id:"metric-challenge",kind:"challenge",title:"Challenge: choose the grouping",assignee:"both",description:"A metric changes meaning depending on how rows are grouped.",steps:["For a daily trend, group by pickup date.","For busiest areas, group by pickup ZIP.","Predict which result has more rows.","Explain why these belong in Gold instead of Silver."]},
    {id:"gold-build",kind:"follow",title:"Build two Gold tables",assignee:"isabel",description:"Turn detailed Silver rows into small summaries.",file:"notebooks/03_gold.py",steps:[`Create ${b.goldMetrics}.`,"Read silver_trips.","Build daily trip count, average fare, and total fare.","Build the same metrics by pickup ZIP.","Save both Gold tables and preview them."],code:`from pyspark.sql import functions as F\n\nsilver = spark.table("${table("silver_trips")}")\n\ndaily = (silver\n    .withColumn("trip_date", F.to_date("tpep_pickup_datetime"))\n    .groupBy("trip_date")\n    .agg(\n        F.count("*").alias("trip_count"),\n        F.round(F.avg("fare_amount"), 2).alias("avg_fare"),\n        F.round(F.sum("fare_amount"), 2).alias("total_fare")\n    ))\n\nby_zip = (silver.groupBy("pickup_zip").agg(\n    F.count("*").alias("trip_count"),\n    F.round(F.avg("fare_amount"), 2).alias("avg_fare"),\n    F.round(F.sum("fare_amount"), 2).alias("total_fare")\n))\n\ndaily.write.mode("overwrite").saveAsTable("${table("gold_daily_metrics")}")\nby_zip.write.mode("overwrite").saveAsTable("${table("gold_zip_metrics")}")`},
    {id:"gold-explain",kind:"challenge",title:"Challenge: explain one Gold row",assignee:"viri",description:"A useful metric should be easy to explain.",steps:["Pick one row from gold_daily_metrics.","Explain the date, count, average, and total.","Find the ZIP with the most trips.","Check that the numbers match your definitions.","Review and merge the pull request."]},
  ],checkpoint:["Define all three metrics","Explain grouping","Both Gold tables exist","Explain one Gold row"]},

  {id:"quality",number:"07",eyebrow:"Challenge",title:"Check the pipeline",summary:"Add a few checks that make mistakes easy to spot.",duration:"60 min",color:"mint",tasks:[
    {id:"quality-learn",kind:"learn",title:"Why add checks?",assignee:"both",description:"A check stops the run and gives a clear message when an important rule is broken.",steps:["Read each check before running it.","Say what problem it catches.","Remember: a failed check is information, not a bad grade."]},
    {id:"quality-build",kind:"follow",title:"Add four clear checks",assignee:"viri",description:"Start small: tables exist, rows exist, and fares make sense.",file:"notebooks/04_quality_checks.py",steps:[`Create ${b.qualityChecks}.`,"Read Bronze, Silver, and Gold.","Add the four checks below.","Run the file from the top.","Look for the success message."],code:`from pyspark.sql import functions as F\n\nbronze = spark.table("${table("bronze_trips")}")\nsilver = spark.table("${table("silver_trips")}")\ngold = spark.table("${table("gold_daily_metrics")}")\n\nassert bronze.count() > 0, "Bronze is empty"\nassert silver.count() > 0, "Silver is empty"\nassert gold.count() > 0, "Gold is empty"\nassert silver.filter(F.col("fare_amount") < 0).count() == 0, "Silver has a negative fare"\n\nprint("All checks passed")`},
    {id:"quality-challenge",kind:"challenge",title:"Challenge: add one check",assignee:"isabel",description:"Choose one extra rule that matters to the project.",steps:["Choose: no negative distance, no repeated Gold date, or Silver not larger than Bronze.","Write one assert statement.","Give it a clear message.","Run all checks and review the pull request."]},
  ],checkpoint:["Explain what each check does","All checks pass","Add one team-created check","The branch is merged"]},

  {id:"dashboard",number:"08",eyebrow:"Follow + challenge",title:"Tell the story with SQL",summary:"Query Gold, choose the right chart, and build a small dashboard.",duration:"2 sessions",color:"lilac",tasks:[
    {id:"sql-first",kind:"follow",title:"Run your first Gold query",assignee:"isabel",description:"SQL reads the small Gold tables directly.",file:"sql/business_queries.sql",steps:["Open SQL Editor.","Choose the shared SQL warehouse.","Run the daily query.","Run the top ZIP query.","Save both queries in business_queries.sql."],code:`SELECT trip_date, trip_count, avg_fare, total_fare\nFROM ${table("gold_daily_metrics")}\nORDER BY trip_date;\n\nSELECT pickup_zip, trip_count, avg_fare\nFROM ${table("gold_zip_metrics")}\nORDER BY trip_count DESC\nLIMIT 10;`},
    {id:"bi-learn",kind:"learn",title:"Where BI fits",assignee:"both",description:"BI tools turn tables and queries into charts people can explore.",steps:["This project uses the AI/BI dashboard inside Databricks.","The dashboard reads the Gold tables through a SQL warehouse.","Tools such as Power BI and Tableau can connect to the same kind of warehouse later.","For this project, stay inside Databricks and focus on the metrics."],links:[{label:"Databricks BI tools",url:"https://docs.databricks.com/aws/en/ai-bi/tools"}]},
    {id:"chart-learn",kind:"learn",title:"Choose a chart that fits",assignee:"both",description:"Use a line for change over time, bars for comparing areas, and one big number for a KPI.",steps:["Watch the dashboard walkthrough.","Match daily trips to a line chart.","Match top ZIPs to a bar chart.","Match total trips to a KPI tile."],links:[videos.dashboard,docs.dashboard]},
    {id:"dashboard-build",kind:"follow",title:"Build the CityRide dashboard",assignee:"isabel",description:"Keep it to three useful views.",steps:[`Create ${b.dashboard}.`,`Create ${c.dashboardName}.`,"Add both Gold tables as datasets.","Add total trips, a daily line chart, and a top-ZIP bar chart.","Add a date filter and publish."],links:[docs.dashboard]},
    {id:"dashboard-challenge",kind:"challenge",title:"Challenge: tell one true story",assignee:"viri",description:"Charts are useful only when you can explain what they show.",steps:["Find the busiest day.","Find the busiest pickup ZIP.","Write two plain sentences about what you found.","Check the chart titles and numbers.","Text Mo the dashboard link."]},
  ],checkpoint:["Run SQL against Gold","Explain why each chart type fits","Publish three useful views","Write two findings"]},

  {id:"automate",number:"09",eyebrow:"Follow along",title:"Run it as one Job",summary:"Connect the notebooks so they run in the right order.",duration:"60 min",color:"blue",tasks:[
    {id:"job-learn",kind:"learn",title:"What a Job does",assignee:"both",description:"A Job saves the order of your tasks so you do not run every notebook by hand.",steps:["Open Jobs & Pipelines.","Look at the empty task graph.","Remember the order: Bronze → Silver → Gold → checks."],links:[docs.jobs]},
    {id:"job-build",kind:"follow",title:"Create the four-task Job",assignee:"viri",description:"Each task starts only after the previous one works.",steps:[`Create ${c.jobName}.`,"Add 01_bronze.","Add 02_silver after Bronze.","Add 03_gold after Silver.","Add 04_quality_checks after Gold.","Choose Serverless compute and run now."],links:[docs.jobs]},
    {id:"job-challenge",kind:"challenge",title:"Challenge: read the run",assignee:"isabel",description:"The graph shows exactly where a run stopped.",steps:["Open the completed run.","Check that all four tasks are green.","Open one task's output.","If one fails, start with the first red task.","Add a screenshot of the green graph to README.md."]},
  ],checkpoint:["Explain the task order","Run all four tasks","Find task output","Save the successful graph"]},

  {id:"devops",number:"10",eyebrow:"Optional · DevOps",title:"Try Terraform",summary:"Learn how code can create a Databricks resource. Do this only after the pipeline works.",duration:"90 min",color:"peach",tasks:[
    {id:"terraform-learn",kind:"learn",title:"What Terraform does",assignee:"both",description:"Terraform reads a configuration file, shows a plan, and then creates what the file describes.",steps:["Watch the Terraform introduction or its first section.","Learn four words: provider, resource, plan, state.","Open the Databricks provider page.","Keep this lab separate from the data notebooks."],links:[videos.terraform,docs.terraform]},
    {id:"terraform-files",kind:"follow",title:"Create a small Terraform lab",assignee:"viri",description:"This lab creates one empty practice schema with Viri's name.",file:"infra/main.tf",steps:["Create feature/terraform-lab.","Create an infra folder with main.tf and variables.tf.","Add the configuration below.","Run terraform fmt, terraform init, and terraform validate.","Commit the files before applying anything."],code:`terraform {\n  required_providers {\n    databricks = {\n      source = "databricks/databricks"\n    }\n  }\n}\n\nprovider "databricks" {}\n\nvariable "catalog_name" { default = "${c.projectCatalog}" }\nvariable "learner_name" { default = "viri" }\n\nresource "databricks_schema" "practice" {\n  catalog_name = var.catalog_name\n  name         = "terraform_\${var.learner_name}"\n  comment      = "Terraform learning schema"\n}` ,links:[docs.terraform]},
    {id:"terraform-plan",kind:"challenge",title:"Challenge: read the plan",assignee:"isabel",description:"A plan is a preview. Read it before creating anything.",steps:["Use your configured Databricks CLI login.","Run terraform plan.","Find the one schema Terraform wants to add.","Check the catalog and schema names.","If login or permission is unavailable in Free Edition, stop after validate and text Mo."],code:`terraform fmt\nterraform init\nterraform validate\nterraform plan`},
    {id:"terraform-apply",kind:"follow",title:"Create and verify the practice schema",assignee:"both",description:"Apply only after the plan shows one expected resource.",steps:["Run terraform apply and confirm the plan.","Open Catalog and find cityride.terraform_viri.","Open terraform.tfstate and identify the saved resource name; do not commit this file.","Add *.tfstate and .terraform/ to .gitignore.","Text Mo before removing or changing the practice schema."],code:`terraform apply`},
  ],checkpoint:["Explain provider, resource, plan, and state","Validate the Terraform files","Read a one-resource plan","Verify the practice schema or document the Free Edition blocker"]},
];

export const glossary=[["Notebook","A page where code runs one cell at a time."],["DataFrame","A table-like object used in Spark code."],["Catalog","The main folder for data."],["Schema","A project area inside a catalog."],["Delta table","The saved table format used here."],["Metric","A number with a clear meaning."],["Job","Tasks saved in the order they should run."],["Terraform","A tool that creates resources from configuration files."],["Pull request","A place to check a change before merging it."]] as const;

export const projectFiles=[{path:"README.md",purpose:"Project notes and results"},{path:"notebooks/00_explore_source.py",purpose:"Python warm-up and source exploration"},{path:"notebooks/01_bronze.py",purpose:"Bronze copy"},{path:"notebooks/02_silver.py",purpose:"Silver cleaning"},{path:"notebooks/03_gold.py",purpose:"Gold metrics"},{path:"notebooks/04_quality_checks.py",purpose:"Simple checks"},{path:"sql/business_queries.sql",purpose:"Dashboard queries"},{path:"tests/test_transformations.py",purpose:"Optional tests"},{path:"docs/data_dictionary.md",purpose:"Rules and metric meanings"},{path:"docs/release_notes.md",purpose:"What changed"}] as const;

export const taskTypeGuide=[
  {title:"Learn",icon:"▶",text:"Read a short idea or watch a simple video. Then explain it in your own words."},
  {title:"Follow along",icon:"1·2",text:"Use the steps and code exactly as shown. Stop after each result and look at it."},
  {title:"Challenge",icon:"★",text:"Try a small task together. The goal is to think, not to get it perfect on the first try."},
] as const;
