import { featureBranches as b, projectConfig as c, type LearnerId } from "@/config/project";

export type Task = { id:string; title:string; description:string; assignee:LearnerId|"both"; code?:string; note?:string; file?:string };
export type Stage = { id:string; number:string; eyebrow:string; title:string; summary:string; duration:string; color:"mint"|"peach"|"lilac"|"blue"; tasks:Task[]; checkpoint:string[] };
const t = (name:string) => `${c.projectCatalog}.${c.developmentSchema}.${name}`;

export const stages:Stage[] = [
  { id:"setup", number:"01", eyebrow:"Before you code", title:"Set up your spaces", summary:"Get access, meet the workspace, and give each teammate a safe Git folder.", duration:"45–60 min", color:"mint", tasks:[
    {id:"access-v",title:"Create your account and accept access",assignee:"viri",description:`Use the Free Edition signup link if needed. Then accept the workspace and ${c.gitProviderName} repository invitations using the invited email.`},
    {id:"access-i",title:"Create your account and accept access",assignee:"isabel",description:`Use the Free Edition signup link if needed. Then accept the workspace and ${c.gitProviderName} repository invitations using the invited email.`},
    {id:"tour",title:"Take the workspace tour together",assignee:"both",description:`Find Workspace, Catalog, Jobs & Pipelines, and SQL Editor. Open ${c.sourceTable} and inspect the columns.`,note:"The samples catalog is read-only source data. Your project catalog is where your team writes managed tables."},
    {id:"git-v",title:"Connect Git and create Viri's own folder",assignee:"viri",description:`Connect ${c.gitProviderName}. Clone the repository inside Viri's personal Workspace folder. Never work from Isabel's Git folder.`},
    {id:"git-i",title:"Connect Git and create Isabel's own folder",assignee:"isabel",description:`Connect ${c.gitProviderName}. Clone the repository inside Isabel's personal Workspace folder. Never work from Viri's Git folder.`},
  ], checkpoint:["Both people can open the workspace and repository","Each person has their own Git folder","Explain samples vs. the project catalog"] },
  { id:"explore", number:"02", eyebrow:"Sprint 1", title:"Meet the taxi data", summary:"Learn the notebook interface together and ask useful questions before transforming anything.", duration:"60–90 min", color:"blue", tasks:[
    {id:"explore-open",title:"Open the exploration notebook",assignee:"both",description:"Open the file, connect Serverless compute, and add a Markdown cell with the project purpose and both names.",file:"notebooks/00_explore_source.py"},
    {id:"explore-read",title:"Read a small sample",assignee:"viri",description:"Run this cell and explain why display() causes Spark to do work.",code:`source_df = spark.read.table("${c.sourceTable}")\ndisplay(source_df.limit(10))`},
    {id:"explore-schema",title:"Inspect shape and schema",assignee:"isabel",description:"Run the schema and row count, then identify what one row represents.",code:`source_df.printSchema()\nprint(f"Rows: {source_df.count():,}")\n\ndisplay(source_df.select(\n    "tpep_pickup_datetime", "tpep_dropoff_datetime",\n    "trip_distance", "fare_amount",\n    "pickup_zip", "dropoff_zip"\n).limit(20))`,note:"Never call toPandas() on the full source table; it moves everything into one Python process."},
    {id:"explore-pr",title:"Record questions and open a PR",assignee:"both",description:`Write three possible quality problems and two business questions. Commit on ${b.sourceExploration}, push, and open a pull request.`},
  ], checkpoint:["Explain what one row represents","Find three possible quality problems","Write two business questions","Open and review the first pull request"] },
  { id:"bronze", number:"03", eyebrow:"Sprint 2", title:"Save the original data", summary:"Viri makes the Bronze copy. Isabel checks that it works more than once.", duration:"60–90 min", color:"peach", tasks:[
    {id:"bronze-branch",title:"Start a clean feature branch",assignee:"viri",description:`Pull newest main, create ${b.bronzeIngestion}, and open the notebook.`,file:"notebooks/01_bronze.py"},
    {id:"bronze-setup",title:"Use the prepared DEV schema",assignee:"viri",description:`The workspace already has cityride.dev and cityride.prod. Select DEV and verify access. If access fails, copy the full error and text ${c.projectOwnerName}.`,code:`PROJECT_CATALOG = "${c.projectCatalog}"\nENV_SCHEMA = "${c.developmentSchema}"\n\nspark.sql(f"USE CATALOG {PROJECT_CATALOG}")\nspark.sql(f"USE SCHEMA {ENV_SCHEMA}")\n\n# Verify access to the prepared schema.\ndisplay(spark.sql(f"SHOW TABLES IN {PROJECT_CATALOG}.{ENV_SCHEMA}"))`},
    {id:"bronze-write",title:"Write the Bronze Delta table",assignee:"viri",description:"Add an ingestion timestamp and source name, then save a stable copy.",code:`from pyspark.sql import functions as F\n\nbronze_df = (spark.read.table("${c.sourceTable}")\n    .withColumn("_ingested_at", F.current_timestamp())\n    .withColumn("_source", F.lit("${c.sourceTable}")))\n\n(bronze_df.write.format("delta").mode("overwrite")\n    .option("overwriteSchema", "true")\n    .saveAsTable("${t("bronze_trips")}"))`},
    {id:"bronze-check",title:"Prove the copy is healthy",assignee:"viri",description:"Run three small assertions before review.",code:`bronze = spark.table("${t("bronze_trips")}")\nassert bronze.count() > 0, "Bronze table is empty"\nassert "_ingested_at" in bronze.columns\nassert "_source" in bronze.columns\nprint("Bronze checks passed")`},
    {id:"bronze-review",title:"Check and merge",assignee:"isabel",description:"Check the table name, the two extra columns, and the result. Merge after Run all works."},
  ], checkpoint:["Bronze contains rows","Audit columns exist","The notebook succeeds top to bottom","The reviewed PR is merged"] },
  { id:"silver-gold", number:"04", eyebrow:"Sprints 3 + 4", title:"Clean data, then shape decisions", summary:"Isabel leads Silver and Gold while Viri challenges each quality rule and metric definition.", duration:"2 sessions", color:"lilac", tasks:[
    {id:"silver-clean",title:"Build the clean Silver table",assignee:"isabel",description:"Create feature/silver-cleaning and make types and filters explicit.",file:"notebooks/02_silver.py",code:`from pyspark.sql import functions as F\nbronze = spark.table("${t("bronze_trips")}")\n\nsilver = (bronze\n .withColumn("pickup_ts", F.to_timestamp("tpep_pickup_datetime"))\n .withColumn("dropoff_ts", F.to_timestamp("tpep_dropoff_datetime"))\n .withColumn("trip_distance", F.col("trip_distance").cast("double"))\n .withColumn("fare_amount", F.col("fare_amount").cast("double"))\n .withColumn("pickup_zip", F.col("pickup_zip").cast("string"))\n .withColumn("trip_minutes", (F.unix_timestamp("dropoff_ts") - F.unix_timestamp("pickup_ts")) / 60)\n .filter(F.col("pickup_ts").isNotNull())\n .filter(F.col("dropoff_ts").isNotNull())\n .filter(F.col("fare_amount") >= 0)\n .filter(F.col("trip_distance") >= 0)\n .filter(F.col("trip_minutes") > 0).dropDuplicates())\n\nsilver.write.format("delta").mode("overwrite")\\\n .option("overwriteSchema", "true")\\\n .saveAsTable("${t("silver_trips")}")`},
    {id:"silver-rules",title:"Document every removed-row rule",assignee:"viri",description:"Compare Bronze and Silver counts. In docs/data_dictionary.md, explain what each filter removes and why.",note:"Removing rows is a business decision. Never hide rejected records without explaining the rule."},
    {id:"gold-daily",title:"Create daily metrics",assignee:"isabel",description:"Build the first decision-ready Gold table.",file:"notebooks/03_gold.py",code:`silver = spark.table("${t("silver_trips")}")\ndaily = (silver.withColumn("trip_date", F.to_date("pickup_ts"))\n .groupBy("trip_date").agg(\n  F.count("*").alias("trip_count"),\n  F.round(F.avg("fare_amount"), 2).alias("avg_fare"),\n  F.round(F.sum("fare_amount"), 2).alias("total_fare"),\n  F.round(F.avg("trip_distance"), 2).alias("avg_distance"),\n  F.round(F.avg("trip_minutes"), 2).alias("avg_trip_minutes")))\n\ndaily.write.format("delta").mode("overwrite")\\\n .option("overwriteSchema", "true")\\\n .saveAsTable("${t("gold_daily_metrics")}")`},
    {id:"gold-zip",title:"Create pickup-area metrics",assignee:"isabel",description:"Group valid trips by pickup ZIP and save gold_zip_metrics.",code:`by_zip = (silver.filter(F.col("pickup_zip").isNotNull())\n .groupBy("pickup_zip").agg(\n  F.count("*").alias("trip_count"),\n  F.round(F.avg("fare_amount"), 2).alias("avg_fare"),\n  F.round(F.sum("fare_amount"), 2).alias("total_fare")))\n\nby_zip.write.format("delta").mode("overwrite")\\\n .option("overwriteSchema", "true")\\\n .saveAsTable("${t("gold_zip_metrics")}")`},
    {id:"gold-review",title:"Validate business meaning together",assignee:"both",description:"Check positive counts, reasonable dates, non-negative fares, and the busiest ZIP. Document every metric definition."},
  ], checkpoint:["Silver has valid times and values","The cleaning rules are written down","Both Gold tables look right","The PRs are checked and merged"] },
  { id:"quality", number:"05", eyebrow:"Sprint 5", title:"Check your work", summary:"Add simple checks so the dashboard only uses good results.", duration:"60 min", color:"mint", tasks:[
    {id:"quality-code",title:"Add pipeline quality checks",assignee:"viri",description:"Put these checks in the quality notebook and run from a fresh session.",file:"notebooks/04_quality_checks.py",code:`from pyspark.sql import functions as F\nbronze = spark.table("${t("bronze_trips")}")\nsilver = spark.table("${t("silver_trips")}")\ndaily = spark.table("${t("gold_daily_metrics")}")\n\nassert bronze.count() > 0, "Bronze is empty"\nassert silver.count() > 0, "Silver is empty"\nassert daily.count() > 0, "Gold is empty"\nassert silver.count() <= bronze.count(), "Silver has extra rows"\n\nbad = silver.filter(F.col("pickup_ts").isNull() |\n (F.col("fare_amount") < 0) | (F.col("trip_distance") < 0) |\n (F.col("trip_minutes") <= 0)).count()\nassert bad == 0, f"Silver contains {bad} invalid rows"\nassert daily.groupBy("trip_date").count()\\\n .filter(F.col("count") > 1).count() == 0, "Duplicate dates"\nprint("All quality checks passed")`},
    {id:"quality-fail",title:"Learn from one failed check",assignee:"isabel",description:"Explain what each check looks for. If one fails, view the rows and fix the earlier step."},
    {id:"quality-review",title:"Check and merge",assignee:"isabel",description:"Make sure the checks catch empty tables, unexpected rows, bad trip values, and repeated dates."},
  ], checkpoint:["All quality checks pass","Both people can explain a useful failure","No check was deleted to make the run green"] },
  { id:"analyze", number:"06", eyebrow:"Sprints 6 + 7", title:"Turn metrics into a story", summary:"Query the Gold layer and build a calm, useful operations dashboard.", duration:"2 sessions", color:"blue", tasks:[
    {id:"sql",title:"Write the business queries",assignee:"isabel",description:"Run daily trend, top pickup areas, and KPI queries in SQL Editor.",file:"sql/business_queries.sql",code:`SELECT trip_date, trip_count, avg_fare, total_fare\nFROM ${t("gold_daily_metrics")} ORDER BY trip_date;\n\nSELECT pickup_zip, trip_count, avg_fare, total_fare\nFROM ${t("gold_zip_metrics")}\nORDER BY trip_count DESC LIMIT 10;\n\nSELECT SUM(trip_count) AS total_trips,\n ROUND(SUM(total_fare), 2) AS total_fare,\n ROUND(SUM(total_fare) / SUM(trip_count), 2) AS fare_per_trip\nFROM ${t("gold_daily_metrics")};`},
    {id:"dashboard",title:"Build the DEV dashboard",assignee:"isabel",description:`Create ${b.dashboard}, then build “${c.dashboardName}”. Add three KPIs, a daily line chart, top-10 ZIP bar chart, and date filter. Use only Gold datasets.`},
    {id:"dashboard-review",title:"Review the story, not just charts",assignee:"viri",description:"Check titles, number formatting, filters, and whether each visual answers a question. Add a Bronze/Silver/Gold explanation."},
    {id:"dashboard-share",title:"Publish and share",assignee:"isabel",description:`Publish, share with Viri, and text ${c.projectOwnerName} the link.`},
  ], checkpoint:["Every chart has a clear title","No chart reads from Bronze","The date filter works","The dashboard answers a real question"] },
  { id:"automate", number:"07", eyebrow:"Sprint 8", title:"Make the pipeline run itself", summary:"Connect the notebooks into one safe, sequential Lakeflow Job and inspect the first run together.", duration:"60–90 min", color:"peach", tasks:[
    {id:"job-create",title:"Create the Job",assignee:"viri",description:`Create “${c.jobName}” in Jobs & Pipelines and choose Serverless compute.`},
    {id:"job-chain",title:"Chain the four tasks",assignee:"viri",description:"Add 01_bronze → 02_silver → 03_gold → 04_quality_checks. Each depends on the one before."},
    {id:"job-watch",title:"Watch the first run",assignee:"both",description:"Run manually, inspect each output, and start debugging at the earliest red task. Do not add a frequent schedule on Free Edition."},
    {id:"job-proof",title:"Capture the green graph",assignee:"isabel",description:"Take a screenshot of the successful task graph and add it to the README."},
  ], checkpoint:["All four tasks run in order","The final quality task is green","README includes the successful graph","There is no quota-wasting schedule"] },
  { id:"release", number:"08", eyebrow:"Release day", title:"Finish version 0.1.0", summary:"Check everything once more, write down what changed, and text Mo when it is ready.", duration:"45–60 min", color:"lilac", tasks:[
    {id:"notes",title:"Write the release notes",assignee:"viri",description:"In docs/release_notes.md, write what changed, how you checked it, and the Free Edition limits."},
    {id:"verify",title:"Verify DEV end to end",assignee:"isabel",description:"Confirm main is current, the Job succeeds, quality passes, dashboard values look right, and the dictionary is current."},
    {id:"tag",title:"Create the release tag",assignee:"viri",description:`Create Git tag v0.1.0 in ${c.gitProviderName} after all required PRs merge.`},
    {id:"prod",title:"Tell Mo it is ready",assignee:"both",description:`Text ${c.projectOwnerName} the Job, dashboard, and release links. Do not edit ${c.projectCatalog}.${c.productionSchema} unless asked.`},
    {id:"reflect",title:"Reflect together",assignee:"both",description:"In README, answer: what did Bronze protect, which Silver rule mattered most, which Gold metric is most useful, what failed first, and what changes for real data?"},
  ], checkpoint:["DEV succeeds end to end","Docs and dashboard are current","v0.1.0 exists","Both people can explain the complete flow"] },
];

export const glossary = [["Workspace","The Databricks website where your team works."],["Notebook","A file with code, notes, and results in small cells."],["Compute","The machines that run your code."],["Spark DataFrame","A table-like object used to work with data."],["Catalog","The main folder that holds your data."],["Schema","A project area inside a catalog."],["Delta table","The saved table format used in this project."],["Job","A saved set of tasks that run in order."],["Branch","Your own copy of the work while you make a change."],["Pull request","A place for your teammate to check your change before it joins main."]] as const;

export const taskChecklists:Record<string,string[]> = {
  "access-v":["Open the configured Databricks Free Edition signup link if you need an account.","Create the account, or sign in with the exact email address that was invited.","Open the workspace invitation and confirm the workspace loads.","Open the GitHub repository invitation and accept it.","Confirm both resources open without an access error."],
  "access-i":["Open the configured Databricks Free Edition signup link if you need an account.","Create the account, or sign in with the exact email address that was invited.","Open the workspace invitation and confirm the workspace loads.","Open the GitHub repository invitation and accept it.","Confirm both resources open without an access error."],
  tour:["Open Workspace and find your personal user folder.","Open Catalog → samples → nyctaxi → trips.","Use Sample Data to preview several rows and column names.","Locate Jobs & Pipelines and SQL Editor in the left navigation.","Tell your teammate why samples is read-only and cityride is writable."],
  "git-v":["Sign in as Viri and open Settings → Linked accounts.","Add the GitHub credential using the Databricks GitHub app/OAuth when offered.","Go to Workspace → Users → Viri's personal folder → Create → Git folder.","Paste https://github.com/MoNakouzi/cityride-analytics and create the folder.","Verify README.md, notebooks, sql, tests, and docs are already present.","Open the Git dialog to prove the clone worked.","Confirm Isabel will not perform Git actions in this folder."],
  "git-i":["Sign in as Isabel and open Settings → Linked accounts.","Add the GitHub credential using the Databricks GitHub app/OAuth when offered.","Go to Workspace → Users → Isabel's personal folder → Create → Git folder.","Paste https://github.com/MoNakouzi/cityride-analytics and create a separate folder.","Verify README.md, notebooks, sql, tests, and docs are already present.","Open the Git dialog to prove the clone worked.","Confirm this is not Viri's Git folder."],
  "explore-open":["Open your personal CityRide Git folder.","Open notebooks/00_explore_source.py.","Choose Connect in the notebook toolbar and select Serverless when prompted.","Add a Markdown cell with the project purpose and both names.","Run the Markdown cell with Shift+Enter."],
  "explore-read":["Create a Python cell below the introduction.","Type or copy the code block into the cell.","Run it with Shift+Enter and wait for the table preview.","Point to one row and describe the taxi trip it represents.","Explain that display() is the action that made Spark execute."],
  "explore-schema":["Add the inspection code in a new Python cell.","Run the cell and expand the schema output.","Write down the timestamp, numeric, and ZIP columns you see.","Look for nulls, negative values, impossible times, or duplicates.","Keep the full dataset in Spark; do not convert it to pandas."],
  "explore-pr":["Pull main in your own Git folder.","Create feature/source-exploration from main.","Add three quality concerns and two business questions.","Run all cells from the top once.","Commit, push, and open a pull request for teammate review."],
  "bronze-branch":["Open the Git dialog in your own folder.","Pull main; remember that pulling clears notebook state.","Create feature/bronze-ingestion from main.","Open notebooks/01_bronze.py and confirm the branch name before editing."],
  "bronze-setup":["Remember that cityride.dev and cityride.prod are already created.","Add the setup code; it selects DEV and does not recreate the catalog.","Run on Serverless compute and verify cityride.dev is visible and writable.","Do not write to cityride.prod unless Mo asks you to.","If PERMISSION_DENIED appears, copy the full error and text Mo."],
  "bronze-write":["Add the ingestion code in the next cell.","Read each chained operation from top to bottom.","Run the cell and wait for the Delta write to finish.","Open Catalog → cityride → dev → bronze_trips and preview rows.","Rerun the cell once to prove overwrite makes this learning pipeline repeatable."],
  "bronze-check":["Add the assertions after the write cell.","Run them and look for “Bronze checks passed”.","If a check fails, inspect the table rather than deleting the assertion.","Use Run all to prove setup, write, and checks work in order."],
  "bronze-review":["Open Viri's pull request in GitHub.","Check the three-part table name and both audit columns.","Confirm the notebook can safely be rerun.","Ask for evidence of a successful Run all.","Approve and merge only when every item passes."],
  "silver-clean":["Pull main after Bronze is merged and create feature/silver-cleaning in Isabel's Git folder.","Add imports and read the Bronze table.","Add each cast, duration, and filter one at a time.","Write silver_trips, preview rows, and run all."],
  "silver-rules":["Record Bronze and Silver row counts.","Calculate how many rows the filters removed.","Review every filter with Isabel and ask what bad record it excludes.","Document the rule and business reason in docs/data_dictionary.md.","Flag any rule whose business meaning is unclear."],
  "gold-daily":["Pull main and create feature/gold-metrics in Isabel's Git folder.","Open notebooks/03_gold.py and read silver_trips.","Create trip_date and calculate all five metrics.","Write and inspect gold_daily_metrics."],
  "gold-zip":["Filter out null pickup ZIP values.","Group by pickup_zip and calculate count, average fare, and total fare.","Write gold_zip_metrics.","Sort by trip_count descending and inspect the top 10.","Add these metric definitions to the data dictionary."],
  "gold-review":["Choose one daily row and explain every number.","Identify the busiest pickup ZIP from the data.","Confirm fares are non-negative and dates are credible.","Agree on the exact wording of each business metric.","Run all, review the PR, and merge."],
  "quality-code":["Pull main and create feature/quality-checks in Viri's Git folder.","Open the existing notebooks/04_quality_checks.py file.","Add imports, layer reads, and every assertion.","Run from a fresh session and save the passing output."],
  "quality-fail":["Read each assertion message aloud.","Temporarily discuss what would make each assertion fail; do not commit a deliberate failure.","When a real failure occurs, open the earliest failing task.","Display the offending rows and trace them back to the transformation.","Fix the transformation, revert any experiment, and rerun the full pipeline."],
  "quality-review":["Confirm Bronze, Silver, and Gold cannot be empty.","Confirm Silver cannot unexpectedly exceed Bronze.","Confirm invalid trips cannot pass into Silver.","Confirm daily Gold has one row per date.","Review the PR and merge after Run all succeeds."],
  sql:["Open SQL Editor and select the shared SQL warehouse.","Paste the queries into sql/business_queries.sql and the editor.","Run one statement at a time using the statement run control.","Inspect daily order, top-10 ordering, and KPI arithmetic.","Commit the SQL file and include result evidence in the PR."],
  dashboard:["Pull main and create feature/dashboard in Isabel's Git folder.","Open Dashboards and create the configured AI/BI dashboard.","Add both Gold datasets and three KPI tiles.","Add the daily line chart and top-10 ZIP bar chart.","Add and test the date filter."],
  "dashboard-review":["Confirm every visual reads from a Gold dataset.","Give every chart a question-oriented title.","Format currency, counts, and dates for quick reading.","Test the date filter and verify the values change.","Add a short text box explaining Bronze, Silver, and Gold."],
  "dashboard-share":["Click Publish and review the published version.","Choose suitable data permissions for this learning workspace.","Share with Viri.","Open the shared view once to confirm permissions work.","Text Mo the published link."],
  "job-create":["Open Jobs & Pipelines → Jobs.","Choose Create job and enter the configured job name.","Create the first Notebook task named 01_bronze.","Select the notebook from your Git folder and choose Serverless compute.","Leave the job without a schedule while learning."],
  "job-chain":["Add 02_silver and set 01_bronze as its dependency.","Add 03_gold and set 02_silver as its dependency.","Add 04_quality_checks and set 03_gold as its dependency.","Inspect the DAG and confirm it is one straight four-task chain.","Confirm every task uses the intended notebook path and Serverless compute."],
  "job-watch":["Click Run now once.","Watch the DAG and open task output as each task completes.","If a task fails, read that task's first useful error before rerunning.","Remember that Free Edition allows five concurrent tasks; this project runs four sequentially.","If quota is exhausted, stop—saved data and settings remain until compute resets."],
  "job-proof":["Wait until every task shows Succeeded.","Open the run details with the full DAG visible.","Capture a screenshot without secrets or personal information.","Add the image and a short caption to README.md.","Commit it on a documentation branch and request review."],
  notes:["Open docs/release_notes.md from current main.","Describe Bronze, Silver, Gold, quality, SQL, dashboard, and Job changes.","Record the successful DEV Job run as test evidence.","List Free Edition quota and non-production limitations.","Commit and open the release documentation PR."],
  verify:["Pull the final main branch into your own Git folder.","Run the DEV Job from start to finish.","Confirm the quality notebook is green.","Compare dashboard KPIs with the Gold SQL results.","Check README, data dictionary, and release notes are current."],
  tag:["Confirm all required PRs are merged into main.","Open the repository's Releases or Tags area.","Create tag v0.1.0 from the final main commit.","Add a short release title and link to the release notes.","Publish the tag and send its URL to Isabel."],
  prod:["Collect the successful Job run, dashboard, and release tag links.","Text the evidence to Mo.","Ask Mo to promote DEV to PROD.","Do not modify cityride.prod unless Mo asks you to.","After promotion, record who ran it and when."],
  reflect:["Meet together after the release.","Answer all five reflection questions in README.md.","Use specific examples from your runs, not generic definitions.","Each person explains the entire Bronze → Silver → Gold flow.","Commit the reflection and celebrate the completed project."],
};

export const taskTypeGuide = [
  {title:"When you see a checklist",icon:"✓",text:"Do the bullets in order. Mark the whole card complete only after its final verification bullet."},
  {title:"When you see a code block",icon:"</>",text:"Open the named notebook or SQL file, type or copy the code, read every line, then run it. Copy buttons are helpers—not a substitute for understanding."},
  {title:"When you see Pair task",icon:"2",text:"Work on a call or side by side. One person drives while the other explains and checks; swap roles at the next pair task."},
  {title:"When you see Review",icon:"↗",text:"The owner pushes a focused branch. The reviewer checks the output and assumptions before approving the pull request."},
  {title:"When you reach a checkpoint",icon:"⚑",text:"Stop and explain the result to each other. If anything is unclear, text Mo. Continue only when the result—not just the code—makes sense."},
];

export const projectFiles = [
  {path:"README.md",purpose:"Project story, run evidence, and final reflection"},
  {path:"notebooks/00_explore_source.py",purpose:"Source exploration"},
  {path:"notebooks/01_bronze.py",purpose:"Repeatable raw-data ingestion"},
  {path:"notebooks/02_silver.py",purpose:"Cleaning and typing rules"},
  {path:"notebooks/03_gold.py",purpose:"Daily and pickup-area metrics"},
  {path:"notebooks/04_quality_checks.py",purpose:"Pipeline quality gates"},
  {path:"sql/business_queries.sql",purpose:"Dashboard and business queries"},
  {path:"tests/test_transformations.py",purpose:"Optional stretch unit tests"},
  {path:"docs/data_dictionary.md",purpose:"Rules and metric definitions"},
  {path:"docs/release_notes.md",purpose:"Release changes, evidence, and limits"},
] as const;

export const conceptPrimer = [
  {layer:"Source",label:c.sourceTable,meaning:"The built-in taxi data you will start with. There is nothing to download or connect.",question:"Start here"},
  {layer:"Bronze",label:"bronze_trips",meaning:"A saved copy of the source, plus the time it was copied. You can always start again from here.",question:"Keep the original"},
  {layer:"Silver",label:"silver_trips",meaning:"The same trips after fixing types, removing duplicates, and filtering values that do not make sense.",question:"Clean the details"},
  {layer:"Gold",label:"daily + ZIP metrics",meaning:"Simple totals and averages that are ready for questions, charts, and the dashboard.",question:"Answer questions"},
] as const;

export const platformConcepts = [
  {title:"How table names work",text:`Databricks uses catalog.schema.table. In ${c.projectCatalog}.${c.developmentSchema}.bronze_trips: cityride is the main folder, dev is the project area, and bronze_trips is the table.`},
  {title:"When Spark runs",text:"Most DataFrame code describes what you want to do. Spark runs it when you display, count, or save the result."},
  {title:"Why use Delta tables?",text:"Delta is the table format used here. It keeps table changes safe and remembers useful details about the table."},
  {title:"DEV and PROD",text:`Do your project work in ${c.projectCatalog}.${c.developmentSchema}. Use ${c.projectCatalog}.${c.productionSchema} only when Mo asks you to.`},
] as const;

export const taskReferences:Record<string,{label:string;url:string}[]> = {
  "access-v":[{label:"Free Edition signup",url:c.databricksFreeEditionSignupUrl},{label:"What Free Edition includes",url:c.freeEditionGuideUrl}],
  "access-i":[{label:"Free Edition signup",url:c.databricksFreeEditionSignupUrl},{label:"What Free Edition includes",url:c.freeEditionGuideUrl}],
  tour:[{label:"Unity Catalog concepts",url:c.unityCatalogGuideUrl},{label:"NYC taxi sample data",url:c.sourceDataUrl}],
  "git-v":[{label:"Git folder setup",url:c.gitFoldersGuideUrl},{label:"CityRide repository",url:c.repositoryUrl}],
  "git-i":[{label:"Git folder setup",url:c.gitFoldersGuideUrl},{label:"CityRide repository",url:c.repositoryUrl}],
  "explore-open":[{label:"Databricks notebooks",url:c.notebooksGuideUrl},{label:"Source data reference",url:c.sourceDataUrl}],
  "explore-read":[{label:"Source data reference",url:c.sourceDataUrl}],
  "bronze-write":[{label:"Medallion architecture",url:c.medallionGuideUrl},{label:"Delta Lake",url:c.deltaLakeGuideUrl}],
  "silver-clean":[{label:"Silver layer explained",url:c.medallionGuideUrl},{label:"Delta Lake",url:c.deltaLakeGuideUrl}],
  "gold-daily":[{label:"Gold layer explained",url:c.medallionGuideUrl}],
  "quality-code":[{label:"Medallion reliability guidance",url:c.medallionGuideUrl}],
  sql:[{label:"AI/BI dashboard datasets",url:c.dashboardsGuideUrl}],
  dashboard:[{label:"Dashboard documentation",url:c.dashboardsGuideUrl}],
  "dashboard-share":[{label:"Publish and share dashboards",url:c.dashboardsGuideUrl}],
  "job-create":[{label:"Lakeflow Jobs concepts",url:c.jobsGuideUrl},{label:"Current Free Edition limits",url:c.freeEditionLimitsUrl}],
  "job-watch":[{label:"Current Free Edition limits",url:c.freeEditionLimitsUrl},{label:"Lakeflow Jobs",url:c.jobsGuideUrl}],
  prod:[{label:"Free Edition limitations",url:c.freeEditionLimitsUrl}],
};
